# -*- coding: utf-8 -*-
"""作業3 - 快速排序演算法實作.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3N9GD78kFH3RhnMcqc8OpP9zuyH3Wn0
"""

def quick_sort(arr, start, end):
    if start >= end:
        return

    pivot_idx = start
    pivot = arr[pivot_idx]
    left = start + 1
    right = end

    print(f"\n📍 QuickSort({start}, {end}) 開始，pivot={pivot} @ index {pivot_idx}")
    print("陣列:", arr)

    while left <= right:
        while left <= right and arr[left] <= pivot:
            left += 1
        while left <= right and arr[right] >= pivot:
            right -= 1

        if left < right:
            print(f"  🔄 交換 arr[{left}]={arr[left]} 和 arr[{right}]={arr[right]}")
            arr[left], arr[right] = arr[right], arr[left]
            print("  ➡️  交換後陣列:", arr)

    print(f"  🔃 將 pivot arr[{pivot_idx}]={arr[pivot_idx]} 和 arr[{right}]={arr[right]} 交換")
    arr[pivot_idx], arr[right] = arr[right], arr[pivot_idx]
    print("  ✅ Pivot 交換後:", arr)

    # 遞迴呼叫左右子陣列
    quick_sort(arr, start, right - 1)
    quick_sort(arr, right + 1, end)


# 測試資料
demo = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
print("🧪 原始資料:", demo)
quick_sort(demo, 0, len(demo) - 1)
print("\n✅ 排序完成:", demo)